#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x249B39D24F25E3B6
#
Name     : libassuan
Version  : 2.5.3
Release  : 17
URL      : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.3.tar.bz2
Source0  : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.3.tar.bz2
Source99 : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.3.tar.bz2.sig
Summary  : IPC library for the GnuPG components
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.1
Requires: libassuan-bin = %{version}-%{release}
Requires: libassuan-lib = %{version}-%{release}
Requires: libassuan-license = %{version}-%{release}
BuildRequires : libgpg-error-dev

%description
If you are building from GIT, run the script
./autogen.sh
first, to make sure that you have all the necessary maintainer tools
are installed and to build the actual configuration files.  If you
have just checked out from GIT, you should add the option "--force" to
autogen.sh so that meta data is noticed by autom4te.cache.  Then run

%package bin
Summary: bin components for the libassuan package.
Group: Binaries
Requires: libassuan-license = %{version}-%{release}

%description bin
bin components for the libassuan package.


%package dev
Summary: dev components for the libassuan package.
Group: Development
Requires: libassuan-lib = %{version}-%{release}
Requires: libassuan-bin = %{version}-%{release}
Provides: libassuan-devel = %{version}-%{release}

%description dev
dev components for the libassuan package.


%package doc
Summary: doc components for the libassuan package.
Group: Documentation

%description doc
doc components for the libassuan package.


%package lib
Summary: lib components for the libassuan package.
Group: Libraries
Requires: libassuan-license = %{version}-%{release}

%description lib
lib components for the libassuan package.


%package license
Summary: license components for the libassuan package.
Group: Default

%description license
license components for the libassuan package.


%prep
%setup -q -n libassuan-2.5.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549894452
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1549894452
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libassuan
cp COPYING %{buildroot}/usr/share/package-licenses/libassuan/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/libassuan/COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/libassuan-config

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libassuan.so
/usr/lib64/pkgconfig/libassuan.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libassuan.so.0
/usr/lib64/libassuan.so.0.8.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libassuan/COPYING
/usr/share/package-licenses/libassuan/COPYING.LIB
